'use client';
import {useState} from 'react';
import {LegalDocument} from '@/components/legal-document';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
export default function Contact(){
 const [kind,setKind]=useState('general'),[name,setName]=useState(''),[email,setEmail]=useState(''),[body,setBody]=useState(''),[goodFaith,setGoodFaith]=useState(false),[accurate,setAccurate]=useState(false),[pending,setPending]=useState(false),[error,setError]=useState(''),[reference,setReference]=useState('');
 const submit=async()=>{setPending(true);setError('');try{const r=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,name,email,body,goodFaith,accurate}),signal:AbortSignal.timeout(20000)});const result=await r.json() as {error?:string;reference:string};if(!r.ok)throw new Error(result.error||'Your request could not be submitted.');setReference(result.reference);}catch(e){setError((e as Error).message);}finally{setPending(false);}};
 return <LegalDocument title="Contact the operator"><p>Questions, privacy requests, copyright complaints, and moderation appeals go privately to Tiernan Lindauer. You do not need an account. Include a reply email; responses are handled individually, so please allow time.</p>{reference?<section role="status"><h2>Request received</h2><p>Your reference is <strong>{reference}</strong>. Save it for any follow-up. Your request is in the operator’s private inbox; this receipt does not confirm a legal determination or promise immediate action.</p><Button variant="outline" onClick={()=>{setReference('');setBody('');}}>New request</Button></section>:<form className="contact-form" onSubmit={e=>{e.preventDefault();void submit();}}><label className="field-label">Topic<select className="form-select" value={kind} onChange={e=>setKind(e.target.value)}><option value="general">General question / moderation appeal</option><option value="privacy">Privacy request</option><option value="copyright">Copyright complaint</option></select></label><label className="field-label">{kind==='copyright'?'Your legal name / electronic signature':'Your name'}<Input value={name} onChange={e=>setName(e.target.value)} minLength={2} maxLength={100} required/></label><label className="field-label">Reply email<Input type="email" value={email} onChange={e=>setEmail(e.target.value)} maxLength={254} required autoComplete="email"/></label><label className="field-label">{kind==='copyright'?'Identify your copyrighted work, the specific infringing URLs, and the action requested':'Your request and relevant URLs or references'}<Textarea value={body} onChange={e=>setBody(e.target.value)} minLength={20} maxLength={5000} rows={8} required/></label>{kind==='copyright'&&<><p className="fine-print">Include enough detail to locate the material and identify your rights, plus a mailing address and phone number if needed for a formal notice. Do not post this information publicly. This form is a direct complaints channel; OpenDraft is not claiming a registered DMCA agent or safe-harbor status.</p><label className="settings-check"><input type="checkbox" required checked={goodFaith} onChange={e=>setGoodFaith(e.target.checked)}/>I have a good-faith belief that the disputed use is not authorized by the rights holder, its agent, or law.</label><label className="settings-check"><input type="checkbox" required checked={accurate} onChange={e=>setAccurate(e.target.checked)}/>The information is accurate and, under penalty of perjury, I am the rights holder or authorized to act for them. My name above is my electronic signature.</label></>}{error&&<p className="form-error" role="alert">{error}</p>}<p className="fine-print">Your details are used to handle this request as described in the privacy policy.</p><Button disabled={pending}>{pending?'Submitting…':'Send private request'}</Button></form>}</LegalDocument>;
}
