import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {mkdirSync} from 'node:fs';
mkdirSync('.sites-runtime/tests',{recursive:true});
await build({entryPoints:['lib/queue-forecast.ts','hooks/use-auto-critique-check.ts'],outdir:'.sites-runtime/tests/forecast',outExtension:{'.js':'.mjs'},bundle:true,format:'esm',platform:'node',packages:'external'});
const {estimateCompletion}=await import('../.sites-runtime/tests/forecast/lib/queue-forecast.mjs');
const {critiqueCheckDelay,cleanCritiqueDraft}=await import('../.sites-runtime/tests/forecast/hooks/use-auto-critique-check.mjs');
const day=86400000,rates={observedMs:10*day,promotions:10,completions:5,completedTargets:10,roomSlots:4};
assert.deepEqual(estimateCompletion(2,2,rates),{lowMs:5*day,highMs:20*day,promotionsPerDay:1,completionsPerDay:.5});
assert.equal(estimateCompletion(2,2,{...rates,promotions:2}),null);
assert.equal(estimateCompletion(2,2,{...rates,completions:2}),null);
assert.equal(estimateCompletion(2,2,{...rates,observedMs:day-1}),null);
assert.equal(estimateCompletion(NaN,2,rates),null);
assert.ok(estimateCompletion(1,2,rates).lowMs<estimateCompletion(3,2,rates).lowMs);
assert.ok(estimateCompletion(2,1,rates).lowMs<estimateCompletion(2,2,rates).lowMs);
assert.ok(estimateCompletion(2,2,{...rates,completions:10,completedTargets:20}).highMs<estimateCompletion(2,2,rates).highMs);
assert.equal(critiqueCheckDelay(10000,0),5000);
assert.equal(critiqueCheckDelay(10000,9000),5000);
assert.equal(critiqueCheckDelay(10000,9000,80000),70000);
const clean=cleanCritiqueDraft({overall:'My own feedback',strengths:'',suggestions:'',annotations:[{kind:'comment',quote:'Hi',body:'A note',para:0,start:0,end:2,userId:'private',author:'Writer',id:'local-1'}]});
assert.deepEqual(Object.keys(clean.annotations[0]).sort(),['body','end','kind','para','quote','start']);
console.log('Queue forecast and automatic check scheduling assertions passed.');
