'use client';
import {useEffect,useState,useCallback} from 'react';
import {BookOpen, Feather, LayoutGrid, Sparkles, FileText, MessageSquare, Users, Bookmark, CircleHelp, Plus, Search, SlidersHorizontal, Clock, ChevronRight, Sun, Bell, ChevronsUpDown, CodeXml, Check, LoaderCircle, LogIn, Download, Settings, ArrowLeft, Quote, Flag, Heart, X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {sampleWorks,sampleCircles,genres,Work,Review,Circle,wordCount} from './data';
import {Editor,Reader,Circles,Guide,Profile,FeedbackList} from './workshop-views';
export type Snapshot={user:{id:string;name:string;bio:string;credits:number}|null;works:Work[];reviews:(Review&{helpful:number;reward:number})[];bookmarks:string[];circles:Circle[];posts:{id:string;circleId:string;userId:string;author:string;body:string;createdAt:number}[];events:{id:string;amount:number;reason:string;createdAt:number}[]};
export type Act=(body:Record<string,unknown>,message?:string)=>Promise<boolean>;
const initial:Snapshot={user:null,works:sampleWorks,reviews:[],bookmarks:[],circles:sampleCircles,posts:[],events:[]};
const navItems=[{icon:LayoutGrid,label:'Explore'},{icon:FileText,label:'My writing'},{icon:MessageSquare,label:'My critiques'},{icon:Users,label:'Writing circles'},{icon:Bookmark,label:'Saved works'}];
export default function Workshop(){
 const [data,setData]=useState<Snapshot>(initial),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(''),[view,setView]=useState('Explore'),[selected,setSelected]=useState(''),[genre,setGenre]=useState('All genres'),[search,setSearch]=useState(''),[tab,setTab]=useState('In the spotlight'),[sort,setSort]=useState('Recommended'),[busy,setBusy]=useState(false),[toast,setToast]=useState(''),[editor,setEditor]=useState<Work|null>(null),[about,setAbout]=useState(false),[login,setLogin]=useState(false),[withdraw,setWithdraw]=useState<Work|null>(null);
 const load=useCallback(async()=>{setLoadError('');try{const r=await fetch('/api/workshop');const d=await r.json() as Snapshot & {error?:string};if(!r.ok)throw new Error(d.error);setData(d);}catch(e){setLoadError((e as Error).message||'The workshop could not load.');}finally{setLoading(false)}},[]);
 useEffect(()=>{void load();const hash=()=>{const h=decodeURIComponent(location.hash.slice(1));if(h.startsWith('read/')){setSelected(h.slice(5));setView('Read & critique')}else if(h){setView(h);setSelected('')}};hash();window.addEventListener('hashchange',hash);return()=>window.removeEventListener('hashchange',hash)},[load]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),5500);return()=>clearTimeout(timer)},[toast]);
 const go=(v:string,id='')=>{setView(v);setSelected(id);location.hash=id?'read/'+id:v;window.scrollTo({top:0,behavior:'smooth'})};
 const act:Act=async(body,message)=>{if(!data.user){setLogin(true);return false}if(busy)return false;setBusy(true);try{const r=await fetch('/api/workshop',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json() as Snapshot & {error?:string};if(!r.ok){if(r.status===401)setLogin(true);throw new Error(d.error)}setData(d);if(message)setToast(message);return true}catch(e){setToast((e as Error).message||'Could not save. Please try again.');return false}finally{setBusy(false)}};
 const newDraft=()=>{if(!data.user){setLogin(true);return}setEditor({id:crypto.randomUUID(),authorId:data.user.id,author:data.user.name,title:'',genre:'Literary fiction',kind:'Short story',stage:'First draft',content:'',request:'',status:'draft',reviews:0,version:1,createdAt:Date.now(),words:0,warning:''})};
 const uid=data.user?.id;const credits=data.user?.credits??5;const own=data.works.filter(w=>w.authorId===uid&&w.status!=='withdrawn');const received=data.reviews.filter(r=>data.works.some(w=>w.id===r.workId&&w.authorId===uid));
 let works=data.works.filter(w=>!['draft','withdrawn'].includes(w.status)&&(genre==='All genres'||w.genre===genre)&&(!search||(w.title+' '+w.author+' '+w.content+' '+w.request).toLowerCase().includes(search.toLowerCase())));
 if(view==='Saved works')works=works.filter(w=>data.bookmarks.includes(w.id));else if(tab!=='All works')works=works.filter(w=>w.status===(tab==='Up next'?'queued':'spotlight'));
 if(sort==='Shortest first')works.sort((a,b)=>a.words-b.words);if(sort==='Newest first')works.sort((a,b)=>b.createdAt-a.createdAt);if(sort==='Needs feedback')works.sort((a,b)=>a.reviews-b.reviews||a.createdAt-b.createdAt);
 const selectedWork=data.works.find(w=>w.id===selected);
 return <div className="app-shell"><a href="#main-content" className="skip-link">Skip to content</a><aside className="sidebar"><a href="/" className="brand" aria-label="OpenDraft home"><BookOpen/><span>OpenDraft<span className="brand-dot">.</span></span></a><div className="workspace-label">YOUR WRITING SPACE</div><nav aria-label="Main navigation">{navItems.map(({icon:Icon,label})=><button title={label} aria-label={label} aria-current={view===label?'page':undefined} className={'nav-item '+(view===label?'active':'')} onClick={()=>go(label)} key={label}><Icon size={19}/>{label}{label==='Explore'&&<span className="nav-marker"/>}</button>)}</nav><div className="sidebar-divider"/><button title="How it works" aria-label="How it works" className={'nav-item '+(view==='How it works'?'active':'')} onClick={()=>go('How it works')}><CircleHelp size={19}/>How it works</button><div className="sidebar-bottom"><button className="open-source" onClick={()=>setAbout(true)}><CodeXml size={19}/><div>Good writing. Open to everyone.<small>Free, open source, community first.</small></div></button><button className="profile" onClick={()=>data.user?go('Your profile'):setLogin(true)}><span className="avatar peach">{data.user?.name[0]?.toUpperCase()||'Y'}</span><span>{data.user?.name||'Your writing space'}<small>{data.user?'Your next draft starts here':'Make yourself at home'}</small></span><ChevronsUpDown size={15}/></button></div></aside>
 <div className="main-shell"><header className="topbar"><div className="breadcrumb"><span className="breadcrumb-label">The workshop</span> <ChevronRight size={14}/><strong>{view}</strong></div><div className="top-actions"><button className="credit-pill" onClick={()=>go('Credit history')}><Sparkles size={15}/>{credits} credits</button><button aria-label="Feedback inbox" title="Feedback inbox" className="icon-button" onClick={()=>go('Feedback inbox')}><Bell size={19}/>{received.length>0&&<span className="notification-count">{received.length}</span>}</button><button aria-label="Your profile" className="avatar peach small" onClick={()=>data.user?go('Your profile'):setLogin(true)}>{data.user?.name[0]?.toUpperCase()||'Y'}</button></div></header><main id="main-content">
 {loadError&&<div className="error-banner" role="alert"><span>{loadError} Showing example stories until the workshop reconnects.</span><Button variant="outline" onClick={()=>void load()}>Try again</Button></div>}
 {loading&&<div className="loading-indicator" role="status"><LoaderCircle size={14} className="animate-spin"/>Connecting to the workshop…</div>}
 {view!=='Read & critique'&&<div className="page-heading"><div><div className="eyebrow">A LITTLE FEEDBACK. A BETTER NEXT DRAFT.</div><h1>{view==='Explore'?'Find your next great read.':view==='My writing'?'Your words. Their next chapter.':view==='Writing circles'?'Find your kind of writers.':view==='Saved works'?'Good reads, kept close.':view==='My critiques'?'A fresh pair of eyes.':view==='How it works'?'A fair exchange of perspectives.':view==='Feedback inbox'?'Fresh eyes on your writing.':view==='Credit history'?'Every critique counts.':'A writer, in your own words.'}</h1><p>{view==='Explore'?'Fresh perspectives for their work. A little inspiration for yours.':view==='My writing'?'From the first uncertain sentence to a draft worth sharing.':view==='Writing circles'?'Small circles. Shared obsessions. Better stories.':view==='My critiques'?'The feedback you give is part of your writing practice, too.':view==='Saved works'?'Pick up where inspiration left you.':view==='Feedback inbox'?'Thoughtful perspectives to take into your next revision.':view==='How it works'?'Good feedback is a gift. Here, everyone gets a turn.':view==='Credit history'?'Earn by giving feedback. Spend on your next draft.':'A little introduction for the people reading your work.'}</p></div>{!['Your profile','How it works','Credit history'].includes(view)&&<Button className="primary-button" onClick={newDraft}><Plus size={18}/>Share your writing</Button>}</div>}
 {(view==='Explore'||view==='Saved works')&&<>{view==='Explore'&&<section className="welcome-banner"><div className="banner-icon"><Sun size={38} strokeWidth={1.3}/></div><div><h2>Better writing starts with a conversation.</h2><p>Give thoughtful feedback. Earn credits. Get fresh eyes on your own work.</p></div><button onClick={()=>go('How it works')}>See how it works <ChevronRight size={16}/></button></section>}
 <div className="content-grid"><section className="explore"><div className="section-heading"><div><h2>{view==='Explore'?<Sparkles size={21}/>:<Bookmark size={21}/>} {view==='Explore'?'The spotlight':'Your reading shelf'}</h2><p>{view==='Explore'?'A few good drafts, ready for your perspective.':`${data.bookmarks.length} saved ${data.bookmarks.length===1?'work':'works'}. A perspective waiting to happen.`}</p></div><span className="live-label">EVERY VOICE GETS A TURN</span></div>{view==='Explore'&&<Tabs value={tab} onValueChange={setTab}><TabsList variant="line" className="work-tabs">{['In the spotlight','Up next','All works'].map(t=><TabsTrigger key={t} value={t}>{t}{t==='In the spotlight'&&<span className="tab-count">{data.works.filter(w=>w.status==='spotlight').length}</span>}</TabsTrigger>)}</TabsList><TabsContent value={tab} className="sr-only">{tab} writing</TabsContent></Tabs>}
 <div className="filters"><div className="search-box"><Search size={17}/><Input aria-label="Search writing" placeholder="Find a story or a writer…" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="filter-select"><SlidersHorizontal size={16}/><select aria-label="Filter by genre" value={genre} onChange={e=>setGenre(e.target.value)}>{genres.map(g=><option key={g}>{g}</option>)}</select></div></div><div className="result-toolbar"><span>{works.length} {works.length===1?'work':'works'} {view==='Explore'&&tab==='Up next'?'in the queue':'to discover'}</span><select aria-label="Sort works" value={sort} onChange={e=>setSort(e.target.value)}>{['Recommended','Needs feedback','Newest first','Shortest first'].map(s=><option key={s}>{s}</option>)}</select></div>
 {tab==='Up next'&&view==='Explore'&&<div className="queue-note">First in, first read. A new work enters the spotlight when a current piece receives three critiques.</div>}
 <div className="work-grid">{works.map((w,i)=><WorkCard key={w.id} work={w} index={i} saved={data.bookmarks.includes(w.id)} busy={busy} onSave={()=>void act({action:'bookmark',workId:w.id,saved:!data.bookmarks.includes(w.id)},data.bookmarks.includes(w.id)?'Removed from your reading shelf.':'Saved to your reading shelf.')} onRead={()=>go('Read & critique',w.id)}/>)}{!works.length&&<Empty title={view==='Saved works'?'Keep a good read for later.':'No drafts here just yet.'} description={search||genre!=='All genres'?'Try another search or genre.':'Explore the workshop and bookmark a story you’d like to return to.'} action={()=>{setSearch('');setGenre('All genres');go('Explore');setTab('All works')}} label="Explore writing"/>}</div>
 <p className="example-note">Stories labeled “Example” are original starter pieces for exploring the workshop.</p></section><aside className="right-rail"><section className="credit-card"><span className="eyebrow">YOUR CRITIQUE CREDITS</span><div className="credit-number">{credits}<span>credits</span><Sparkles size={26}/></div><p>A thoughtful critique goes a long way.<br/>For their draft, and for yours.</p><div className="credit-rule"><Sparkles size={15}/><span>Earn <strong>2 credits</strong> in the spotlight</span></div><div className="credit-rule"><Feather size={15}/><span>Share a draft for <strong>5 credits</strong></span></div><button className="text-link" onClick={()=>go('Credit history')}>A fair exchange <ChevronRight size={15}/></button></section><section className="rail-section"><div className="rail-heading"><h3>Find your people</h3><Users size={19}/></div><p>Small circles. Shared obsessions.<br/>Better stories.</p>{data.circles.slice(0,3).map((c,i)=><button className="circle-preview" key={c.id} onClick={()=>go('Writing circles')}><span className={'circle-symbol tone-'+i}>{c.name[0]}</span><span><strong>{c.name}</strong><small>{c.genre}</small></span><ChevronRight size={15}/></button>)}<button className="text-link" onClick={()=>go('Writing circles')}>Explore writing circles <ChevronRight size={15}/></button></section><section className="tip-card"><span><Feather size={16}/>A NOTE ON GOOD FEEDBACK</span><h3>Be specific. Be kind.<br/>Help the next draft.</h3><p>“The dialogue feels natural” is good. Showing where and why is even better.</p></section></aside></div></>}
 {view==='Read & critique'&&(selectedWork?<Reader work={selectedWork} data={data} act={act} busy={busy} back={()=>go('Explore')} onSignIn={()=>setLogin(true)}/>:<Empty title="This story isn’t available." description="It may have been withdrawn by its writer." label="Back to the workshop" action={()=>go('Explore')}/>)}
 {view==='My writing'&&(own.length?<div className="writing-list">{own.map(w=><article className="writing-row" key={w.id}><span className="writing-icon"><FileText size={23}/></span><div><span className={'status-label '+w.status}>{w.status==='spotlight'?'In the spotlight':w.status==='queued'?`In queue · ${data.works.filter(x=>x.status==='queued'&&x.createdAt<w.createdAt).length+1} in line`:w.status==='open'?'Open for feedback':'Private draft'}</span><h2>{w.title}</h2><p>{w.genre} · {w.words} words · {w.reviews} critiques</p></div><div className="writing-actions"><Button variant="outline" onClick={()=>w.status==='draft'?setEditor(w):go('Read & critique',w.id)}>{w.status==='draft'?'Keep writing':'Read feedback'}</Button>{w.status!=='draft'&&<Button variant="ghost" onClick={()=>setEditor({...w,id:crypto.randomUUID(),status:'draft',title:w.title+' (revision)',reviews:0})}>New revision</Button>}<button className="icon-button" title="Withdraw work" aria-label={'Withdraw '+w.title} onClick={()=>setWithdraw(w)}><X size={18}/></button></div></article>)}</div>:<Empty title="Every story starts somewhere." description="Save a private draft for free, or share your writing with the workshop for five credits." label="Start a draft" action={newDraft}/>)}
 {(view==='My critiques'||view==='Feedback inbox')&&<FeedbackList reviews={view==='My critiques'?data.reviews.filter(r=>r.userId===uid):received} data={data} act={act} busy={busy} onRead={id=>go('Read & critique',id)} received={view==='Feedback inbox'} onExplore={()=>go('Explore')}/>}
 {view==='Writing circles'&&<Circles data={data} act={act} busy={busy}/>}
 {view==='How it works'&&<Guide onExplore={()=>go('Explore')} onWrite={newDraft} onAbout={()=>setAbout(true)}/>}
 {view==='Your profile'&&<Profile data={data} act={act} busy={busy} onSignIn={()=>setLogin(true)}/>}
 {view==='Credit history'&&<div className="credit-history"><div className="balance-card"><Sparkles size={28}/><h2>{credits} credits</h2><p>You start with five. Thoughtful critiques keep the exchange going.</p></div><div className="history-row"><span>Welcome to OpenDraft</span><strong>+5</strong></div>{data.events.map(e=><div className="history-row" key={e.id}><span>{e.reason}<small>{new Date(e.createdAt).toLocaleDateString()}</small></span><strong className={e.amount<0?'spent':''}>{e.amount>0?'+':''}{e.amount}</strong></div>)}<Button variant="outline" onClick={()=>go('Explore')}>Find a work to critique</Button></div>}
 <footer>Made for the messy, wonderful process of writing.<button onClick={()=>setAbout(true)}>Always free. Always open.</button></footer></main></div>
 <Dialog open={!!editor} onOpenChange={open=>{if(!open)setEditor(null)}}><DialogContent className="editor-dialog"><DialogTitle>Give your next draft a little room.</DialogTitle><DialogDescription>Save privately for free. Share with the workshop when you’re ready.</DialogDescription>{editor&&<Editor key={editor.id} initial={editor} credits={credits} act={act} busy={busy} close={()=>setEditor(null)} onDone={()=>{setEditor(null);go('My writing')}}/>}</DialogContent></Dialog>
 <Dialog open={login} onOpenChange={setLogin}><DialogContent className="compact-dialog"><DialogTitle>Make yourself at home.</DialogTitle><DialogDescription>Sign in to keep your drafts, give feedback, and find your writing circle. You’ll start with five free credits.</DialogDescription><Button asChild className="primary-button"><a href="/signin-with-chatgpt?return_to=/" target="_top"><LogIn size={17}/>Sign in with ChatGPT</a></Button><p className="fine-print">Your writing belongs to you. No subscriptions. No paid credit packs.</p></DialogContent></Dialog>
 <Dialog open={about} onOpenChange={setAbout}><DialogContent className="compact-dialog"><DialogTitle><BookOpen className="inline mr-2"/>A workshop that belongs to its writers.</DialogTitle><DialogDescription>OpenDraft is free software under the MIT license. Anyone can use, study, modify, and self-host it.</DialogDescription><div className="about-copy"><p>Credits are a way of exchanging attention. They’re earned through critique, never sold. Drafts are private until you publish them to the workshop.</p><p>You keep ownership of your stories and can export your writing and feedback from your profile.</p><p>The original example stories demonstrate the workflow. OpenDraft is an independent project, inspired by the idea of reciprocal writing workshops.</p><span className="license-label"><CodeXml size={16}/>MIT licensed · Built for community</span></div></DialogContent></Dialog>
 <Dialog open={!!withdraw} onOpenChange={open=>{if(!open)setWithdraw(null)}}><DialogContent className="compact-dialog"><DialogTitle>Withdraw “{withdraw?.title}”?</DialogTitle><DialogDescription>This removes the work from workshop listings. Your existing feedback is preserved in your account. Spent credits aren’t refunded.</DialogDescription><div className="form-actions"><Button variant="outline" onClick={()=>setWithdraw(null)}>Keep it here</Button><Button disabled={busy} onClick={async()=>{if(await act({action:'withdraw',workId:withdraw?.id},'Work withdrawn from the workshop.'))setWithdraw(null)}}>Withdraw work</Button></div></DialogContent></Dialog>
 {toast&&<div className="toast" role="status"><MessageSquare size={17}/><span>{toast}</span><button aria-label="Dismiss notification" onClick={()=>setToast('')}><X size={16}/></button></div>}</div>
}
export function Empty({title,description,label,action}:{title:string;description:string;label?:string;action?:()=>void}){return <div className="empty-state"><BookOpen size={30}/><h2>{title}</h2><p>{description}</p>{label&&<Button variant="outline" onClick={action}>{label}</Button>}</div>}
function WorkCard({work:w,index:i,saved,busy,onSave,onRead}:{work:Work;index:number;saved:boolean;busy:boolean;onSave:()=>void;onRead:()=>void}){return <article className="work-card"><div className="card-top"><span className={'genre-tag tone-'+(i%4)}>{w.genre}</span><button disabled={busy} className={'icon-button '+(saved?'is-saved':'')} aria-label={(saved?'Unsave ':'Save ')+w.title} aria-pressed={saved} onClick={onSave}><Bookmark size={18} fill={saved?'currentColor':'none'}/></button></div><h3><button onClick={onRead}>{w.title}</button></h3><div className="byline"><span className={'avatar tone-'+(i%4)}>{w.author.split(' ').slice(0,2).map(s=>s[0]).join('')}</span><span>{w.author}</span><span className="dot">·</span><span>{w.stage}</span></div><p className="excerpt">{w.content.split('\n')[0]}</p><div className="feedback-request"><MessageSquare size={14}/><span>{w.request}</span></div><div className="work-meta"><span><FileText size={14}/>{w.words} words</span><span><Clock size={14}/>{Math.max(1,Math.ceil(w.words/200))} min</span><span>{w.kind}</span></div><div className="card-bottom"><div className="critique-progress"><span className="progress-marks">{[0,1,2].map(x=><i key={x} className={w.reviews>x?'filled':''}/>)}</span><span>{w.reviews} of 3 critiques</span></div><button className="review-link" onClick={onRead}>Read & critique <ChevronRight size={15}/></button></div><div className={'reward '+(w.status!=='spotlight'?'quiet':'')}><Sparkles size={12}/>{w.status==='spotlight'?'+2':'+1'} {w.status==='spotlight'?'credits':'credit'} for a thoughtful critique{w.authorId.startsWith('sample-')&&<span className="example-badge">Example</span>}</div></article>}


