'use client';
import {JevTermsNotice} from './jev-terms-notice';
import {FormEvent,useState} from 'react';
import {AlertCircle,ArrowLeft,Mail} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogDescription,DialogTitle} from '@/components/ui/dialog';

function GoogleIcon(){return <svg width="15" height="15" viewBox="0 0 48 48" aria-hidden="true" focusable="false"><path fill="#EA4335" d="M24 9.5c3.54 0 6.71 1.22 9.21 3.6l6.85-6.85C35.9 2.38 30.47 0 24 0 14.62 0 6.51 5.38 2.56 13.22l7.98 6.19C12.43 13.72 17.74 9.5 24 9.5z"/><path fill="#4285F4" d="M46.98 24.55c0-1.57-.15-3.09-.38-4.55H24v9.02h12.94c-.58 2.96-2.26 5.48-4.78 7.18l7.73 6c4.51-4.18 7.09-10.36 7.09-17.65z"/><path fill="#FBBC05" d="M10.53 28.59c-.48-1.45-.76-2.99-.76-4.59s.27-3.14.76-4.59l-7.98-6.19C.92 16.46 0 20.12 0 24c0 3.88.92 7.54 2.56 10.78l7.97-6.19z"/><path fill="#34A853" d="M24 48c6.48 0 11.93-2.13 15.89-5.81l-7.73-6c-2.15 1.45-4.92 2.3-8.16 2.3-6.26 0-11.57-4.22-13.47-9.91l-7.98 6.19C6.51 42.62 14.62 48 24 48z"/></svg>}

type Mode='login'|'register'|'forgot';
export function AuthDialog({open,onOpenChange,googleConfigured,emailPasswordConfigured,returnTo='/'}:{open:boolean;onOpenChange:(value:boolean)=>void;googleConfigured:boolean;emailPasswordConfigured:boolean;returnTo?:string}){
 const [mode,setMode]=useState<Mode>('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[devUrl,setDevUrl]=useState(''),[busy,setBusy]=useState(false);
 const reset=(next:Mode)=>{setMode(next);setError('');setMessage('');setDevUrl('');setPassword('');setConfirm('');};
 async function submit(event:FormEvent){event.preventDefault();setError('');setMessage('');setDevUrl('');if(mode==='register'&&password!==confirm){setError('The passwords do not match.');return;}setBusy(true);try{const action=mode==='forgot'?'requestReset':mode;const response=await fetch('/api/auth/password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,email,password})});const data=await response.json() as {error?:string;message?:string;devUrl?:string;code?:string};if(!response.ok)throw new Error(data.error||'Sign-in could not be completed.');if(mode==='login'){window.location.assign(returnTo||'/#Dashboard');return;}setMessage(data.message||'Check your email for the next step.');setDevUrl(data.devUrl||'');}catch(reason){setError((reason as Error).message);}finally{setBusy(false);}}
 return <Dialog open={open} onOpenChange={value=>{onOpenChange(value);if(!value)reset('login');}}><DialogContent className="compact-dialog auth-dialog"><DialogTitle>{mode==='login'?'Welcome back.':mode==='register'?'Join the workshop.':'Reset your password.'}</DialogTitle><DialogDescription>{mode==='login'?'Sign in to keep drafting and critiquing.':mode==='register'?'Start with five free critique credits. Your public pen name is set separately.':'We’ll send a one-time reset link if the address has an account.'}</DialogDescription>{mode!=='forgot'&&googleConfigured&&<Button asChild variant="outline" className="auth-provider"><a href={'/api/auth/login?return_to='+encodeURIComponent(returnTo)}><GoogleIcon/>Continue with Google</a></Button>}{mode!=='forgot'&&googleConfigured&&emailPasswordConfigured&&<div className="auth-divider"><span>or</span></div>}{emailPasswordConfigured?<form className="auth-form" onSubmit={submit}><label className="field-label">Email<Input type="email" autoComplete="email" maxLength={254} value={email} onChange={event=>setEmail(event.target.value)} required/></label>{mode!=='forgot'&&<label className="field-label">Password<Input type="password" autoComplete={mode==='register'?'new-password':'current-password'} minLength={12} maxLength={256} value={password} onChange={event=>setPassword(event.target.value)} required/><span className="field-hint">At least 12 characters</span></label>}{mode==='register'&&<label className="field-label">Confirm password<Input type="password" autoComplete="new-password" minLength={12} maxLength={256} value={confirm} onChange={event=>setConfirm(event.target.value)} required/></label>}{error&&<p className="form-error" role="alert"><AlertCircle size={13}/>{error}</p>}{message&&<p className="auth-success" role="status"><Mail size={14}/>{message}</p>}{devUrl&&<a className="text-link" href={devUrl}>Open the development-only email link</a>}<Button className="primary-button" disabled={busy}>{busy?'Working…':mode==='login'?'Sign in with email':mode==='register'?'Create account':'Send reset link'}</Button></form>:!googleConfigured&&<p className="auth-setup-note"><AlertCircle size={13}/>Sign-in is not configured on this deployment.</p>}{emailPasswordConfigured&&<div className="auth-switch">{mode==='login'?<><button type="button" onClick={()=>reset('register')}>Create an email account</button><button type="button" onClick={()=>reset('forgot')}>Forgot password?</button></>:<button type="button" onClick={()=>reset('login')}><ArrowLeft size={13}/>Back to sign in</button>}</div>}<JevTermsNotice/><p className="fine-print">By continuing, you agree to the <a href="/terms">Terms</a> and acknowledge the <a href="/privacy">Privacy policy</a>.</p></DialogContent></Dialog>;
}
