'use client';
import {useEffect,useState} from 'react';
import {Users,UserPlus,ShieldBan,Check,MessageSquare,BarChart3} from 'lucide-react';
import {Button} from './ui/button';
import {Input} from './ui/input';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from './ui/dialog';
import {WriterAvatar} from './writer-avatar';
import {usePagedList,PageMore} from './paged-list';
import {communityAction,useJson} from '@/hooks/use-community';
import type {Reputation} from '@/lib/reputation';
const cache=new Map<string,{value:Reputation;until:number}>(),queued=new Map<string,((value:Reputation|null)=>void)[]>();
let scheduled=false;
function ratingFor(id:string):Promise<Reputation|null>{
 const old=cache.get(id);if(old&&old.until>Date.now())return Promise.resolve(old.value);
 return new Promise(resolve=>{queued.set(id,[...(queued.get(id)||[]),resolve]);if(scheduled)return;scheduled=true;setTimeout(async()=>{
  scheduled=false;const jobs=[...queued];queued.clear();
  for(let offset=0;offset<jobs.length;offset+=20){const part=jobs.slice(offset,offset+20);
   try{const r=await fetch('/api/community?section=reputation&ids='+encodeURIComponent(part.map(([id])=>id).join(',')));if(!r.ok)throw new Error('Unavailable');const data=await r.json() as {items:Reputation[]};for(const [id,listeners] of part){const value=data.items.find(x=>x.id===id)||null;if(value)cache.set(id,{value,until:Date.now()+120000});listeners.forEach(listener=>listener(value));}}
   catch{part.forEach(([,listeners])=>listeners.forEach(listener=>listener(null)));}}
 },8);});
}
export function ReviewerScore({id,full=false}:{id:string;full?:boolean}){
 const [state,setState]=useState<{id:string;value:Reputation|null;done:boolean}>({id:'',value:null,done:false});
 useEffect(()=>{let alive=true;const read=()=>{void ratingFor(id).then(value=>{if(alive)setState({id,value,done:true});});};read();window.addEventListener('opendraft:ratings',read);return()=>{alive=false;window.removeEventListener('opendraft:ratings',read);};},[id]);
 const value=state.id===id?state.value:null;
 if(!full)return <span className="reviewer-score" title="Human ratings of usefulness, specificity, and actionable advice">{value?.eligible?<><BarChart3 size={12}/><b>{value.combined}/100</b><span> · {value.ratings} ratings</span></>:<span>{state.done?'Building reviewer rating':'Reviewer rating…'}</span>}</span>;
 return <section className="reputation-panel"><h2>Feedback quality</h2><p className="fine-print">Rated by writers receiving this reviewer’s critiques. Scores appear after 10 counted ratings from 5 distinct writers.</p>{(['usefulness','specificity','actionability'] as const).map((key,index)=><div className="reputation-row" key={key}><span>{['Useful','Specific','Actionable'][index]}</span><div className="reputation-track" role="meter" aria-label={key} aria-valuemin={0} aria-valuemax={100} aria-valuenow={value?.eligible?value[key]!:undefined} aria-valuetext={value?.eligible?value[key]+'/100':'Not enough ratings yet'}><i style={{width:value?.eligible?value[key]+'%':'0%'}}/></div><b>{value?.eligible?value[key]+'/100':'—'}</b></div>)}<p className="fine-print">{value?value.ratings+' counted ratings from '+value.writers+' writers':'Ratings unavailable right now.'}{value?.eligible?' · Combined '+value.combined+'/100':''}</p><p className="fine-print">One rating contribution per writer/reviewer pair per 30-day period; last 12 months. Credits are separate.</p></section>;
}
export function CritiqueRating({id}:{id:string}){
 const [open,setOpen]=useState(false),[edits,setEdits]=useState<Record<string,number>>({}),[pending,setPending]=useState(false),[note,setNote]=useState('');
 const resource=useJson<{rating:Record<string,number>|null}>('/api/community?section=rating&id='+encodeURIComponent(id),open);
 const value=(key:string)=>edits[key]||resource.data?.rating?.[key]||0;
 const save=async(remove=false)=>{setPending(true);setNote('');try{await communityAction(remove?{action:'removeRating',id}:{action:'rateCritique',id,usefulness:value('usefulness'),specificity:value('specificity'),actionability:value('actionability')});cache.clear();window.dispatchEvent(new Event('opendraft:ratings'));resource.refresh();setOpen(false);}catch(e){setNote((e as Error).message);}finally{setPending(false);}};
 return <><Button type="button" variant="outline" onClick={()=>{setEdits({});setNote('');setOpen(true);}}><BarChart3 size={13}/>Rate this critique</Button><Dialog open={open} onOpenChange={v=>{if(!pending)setOpen(v);}}><DialogContent className="compact-dialog"><DialogTitle>How did this critique help?</DialogTitle><DialogDescription>Consider concrete examples, engagement with your question, and advice you can use. Your individual ratings stay private; sufficient ratings form the reviewer’s public aggregate.</DialogDescription>{resource.error?<p role="alert">{resource.error}</p>:resource.loading?<p>Loading your rating…</p>:<>{(['usefulness','specificity','actionability'] as const).map((key,index)=><fieldset className="rating-question" key={key}><legend>{['Useful for your revision','Specific to your writing','Actionable suggestions'][index]}</legend><div>{[1,2,3,4,5].map(score=><button type="button" key={score} disabled={pending} aria-label={key+': '+score+' of 5'} aria-pressed={value(key)===score} onClick={()=>setEdits(old=>({...old,[key]:score}))}>{score}</button>)}</div></fieldset>)}<p className="fine-print">1 = limited · 3 = helpful · 5 = excellent. Edit for seven days, or remove your rating later.</p>{note&&<p className="form-error" role="alert">{note}</p>}<div className="form-actions">{resource.data?.rating&&<Button type="button" variant="outline" disabled={pending} onClick={()=>void save(true)}>Remove rating</Button>}<Button type="button" disabled={pending||!value('usefulness')||!value('specificity')||!value('actionability')} onClick={()=>void save()}>Save rating</Button></div></>}</DialogContent></Dialog></>;
}
type Relationship={available:boolean;status:string;incoming:boolean;blocked:boolean;unavailable:boolean};
export function FriendControls({id,uid,onMessage}:{id:string;uid:string;onMessage?:(id:string)=>void}){
 const enabled=!!uid&&id!==uid&&!id.startsWith('sample-');
 const resource=useJson<Relationship>('/api/community?section=relationship&id='+encodeURIComponent(id),enabled);
 const [pending,setPending]=useState(false),[error,setError]=useState(''),[blockConfirm,setBlockConfirm]=useState(false);
 const run=async(action:string)=>{setPending(true);setError('');try{await communityAction({action,id});resource.refresh();window.dispatchEvent(new Event('opendraft:friends'));setBlockConfirm(false);}catch(e){setError((e as Error).message);}finally{setPending(false);}};
 if(!enabled)return null;
 const r=resource.data;
 return <div className="friend-controls">{resource.error?<p role="alert">{resource.error}</p>:!r?<span className="fine-print">Loading member controls…</span>:r.blocked?<><span className="fine-print">You blocked this writer.</span><Button variant="outline" disabled={pending} onClick={()=>void run('unblock')}>Unblock</Button></>:!r.available||r.unavailable?<span className="fine-print">This member is unavailable.</span>:<>
  {r.status==='accepted'?<span className="friend-status"><Check size={14}/>Friends</span>:r.status==='pending'?r.incoming?<><Button disabled={pending} onClick={()=>void run('acceptFriend')}>Accept friend</Button><Button variant="outline" disabled={pending} onClick={()=>void run('rejectFriend')}>Decline</Button></>:<><span className="fine-print">Request sent</span><Button variant="outline" disabled={pending} onClick={()=>void run('cancelFriend')}>Cancel request</Button></>:<Button variant="outline" disabled={pending} onClick={()=>void run('friendRequest')}><UserPlus size={14}/>{r.status==='rejected'?'Request again':'Add friend'}</Button>}
  {onMessage&&<Button variant="outline" onClick={()=>onMessage(id)}><MessageSquare size={14}/>Message</Button>}
  <details className="member-more"><summary>More</summary>{r.status==='accepted'&&<Button variant="ghost" disabled={pending} onClick={()=>void run('removeFriend')}>Remove friend</Button>}<Button variant="ghost" disabled={pending} onClick={()=>setBlockConfirm(true)}><ShieldBan size={13}/>Block writer</Button></details>
 </>}{error&&<p className="form-error" role="alert">{error}</p>}<Dialog open={blockConfirm} onOpenChange={setBlockConfirm}><DialogContent className="compact-dialog"><DialogTitle>Block this writer?</DialogTitle><DialogDescription>This ends your friendship and prevents direct messages and new friend requests in either direction. Your message history stays available for reporting. Shared circle discussions remain visible.</DialogDescription><div className="form-actions"><Button variant="outline" onClick={()=>setBlockConfirm(false)}>Cancel</Button><Button disabled={pending} onClick={()=>void run('block')}>Block writer</Button></div></DialogContent></Dialog></div>;
}
export function FriendsView({onAuthor,onMessage,incomingRequests=0}:{onAuthor:(id:string)=>void;onMessage:(id:string)=>void;incomingRequests?:number}){
 const [mode,setMode]=useState(()=>incomingRequests>0?'incoming':'accepted'),[revision,setRevision]=useState(0),[error,setError]=useState(''),[pending,setPending]=useState('');
 const page=usePagedList<{id:string;userId:string;name:string;status:string}>('/api/community?section=friends&mode='+mode+(mode==='incoming'?'&pending='+incomingRequests:''),true,revision);
 useEffect(()=>{const changed=()=>setRevision(n=>n+1);window.addEventListener('opendraft:friends',changed);return()=>window.removeEventListener('opendraft:friends',changed);},[]);
 const run=async(action:string,id:string)=>{setPending(id);setError('');try{await communityAction({action,id});setRevision(n=>n+1);window.dispatchEvent(new Event('opendraft:friends'));}catch(e){setError((e as Error).message);}finally{setPending('');}};
 return <section className="sheet"><div className="sheet-head"><h1><Users size={25}/>Friends</h1></div><div className="sheet-toolbar friend-tabs">{[['accepted','Friends'],['incoming','Requests'],['outgoing','Sent'],['blocked','Blocked']].map(([key,label])=><button key={key} aria-pressed={mode===key} className={mode===key?'active':''} onClick={()=>setMode(key)}>{label}{key==='incoming'&&incomingRequests>0&&<span className="request-count" aria-label={incomingRequests+' pending friend requests'}>{incomingRequests}</span>}</button>)}</div><div className="sheet-body">{error&&<p className="form-error" role="alert">{error}</p>}{!page.items.length&&!page.loading&&!page.error&&<p className="fine-print">{mode==='incoming'?'No pending friend requests.':mode==='outgoing'?'No sent requests.':mode==='blocked'?'You haven’t blocked anyone.':'No friends yet. Open a writer’s profile to send a friend request.'}</p>}{page.items.map(person=><article className="friend-row" key={person.id}><WriterAvatar name={person.name} userId={person.userId}/><button className="author-link" onClick={()=>onAuthor(person.userId)}>{person.name}</button><div className="friend-row-actions">{mode==='accepted'?<><Button variant="outline" onClick={()=>onMessage(person.userId)}>Message</Button><Button variant="ghost" disabled={pending===person.userId} onClick={()=>void run('removeFriend',person.userId)}>Remove</Button></>:mode==='incoming'?<><Button disabled={pending===person.userId} onClick={()=>void run('acceptFriend',person.userId)}>Accept</Button><Button variant="outline" disabled={pending===person.userId} onClick={()=>void run('rejectFriend',person.userId)}>Decline</Button></>:mode==='blocked'?<Button variant="outline" disabled={pending===person.userId} onClick={()=>void run('unblock',person.userId)}>Unblock</Button>:<><span className="fine-print">{person.status==='rejected'?'Declined':'Pending'}</span>{person.status==='pending'&&<Button variant="outline" disabled={pending===person.userId} onClick={()=>void run('cancelFriend',person.userId)}>Cancel</Button>}</>}</div></article>)}<PageMore page={page} label="More members"/></div></section>;
}
export function AccountControls({uid,deletionOnly=false}:{uid:string;deletionOnly?:boolean}){
 const resource=useJson<{friendsOnly:boolean}>('/api/community?section=status',!deletionOnly);
 const [open,setOpen]=useState(false),[confirmation,setConfirmation]=useState(''),[pending,setPending]=useState(false),[error,setError]=useState('');
 const settings=async(friendsOnly:boolean)=>{setPending(true);setError('');try{await communityAction({action:'settings',friendsOnly});resource.refresh();}catch(e){setError((e as Error).message);}finally{setPending(false);}};
 const revoke=async()=>{setPending(true);setError('');try{await communityAction({action:'revokeSessions'});location.replace(location.origin+'/');}catch(e){setError((e as Error).message);setPending(false);}};
 const remove=async()=>{setPending(true);setError('');try{await communityAction({action:'deleteAccount',confirmation});try{for(const storage of [localStorage,sessionStorage]){for(const key of Object.keys(storage))if(key.startsWith('opendraft:draft:'+encodeURIComponent(uid)+':')||key==='opendraft:message-drafts:'+uid)storage.removeItem(key);}}catch{/* Deletion succeeded even if browser storage is unavailable. */}location.replace(location.origin+'/');}catch(e){setError((e as Error).message);setPending(false);}};
 return <section className="account-controls">{!deletionOnly&&<><h2>Member controls</h2><label className="settings-check"><input type="checkbox" disabled={pending||!resource.data} checked={resource.data?.friendsOnly||false} onChange={e=>void settings(e.target.checked)}/>Only accepted friends can send me direct messages</label>{resource.error&&<p role="alert">{resource.error}</p>}<p className="fine-print">Friend requests remain available. Blocking stops direct messages and requests in both directions.</p><div className="account-security-actions"><Button type="button" variant="outline" disabled={pending} onClick={()=>void revoke()}>Sign out on every device</Button><span className="fine-print">Immediately revokes all current sessions, including this one.</span></div><p><a className="text-link" href="/privacy">Privacy policy</a> · <a className="text-link" href="/terms">Terms</a> · <a className="text-link" href="/contact">Contact the operator</a></p></>}<Button type="button" variant="outline" className="account-delete" onClick={()=>{setOpen(true);setConfirmation('');setError('');}}>Delete my account</Button><Dialog open={open} onOpenChange={v=>{if(!pending)setOpen(v);}}><DialogContent className="compact-dialog"><DialogTitle>Delete your account permanently?</DialogTitle><DialogDescription>Your profile, manuscript text, critiques you wrote, pictures, friendships, and memberships will be removed. Your messages are replaced with removal notices. Other writers’ critiques and restricted moderation evidence may remain. Your circles become workshop-managed. Older sessions are revoked.</DialogDescription><a className="text-link" href="/api/export">Export your writing and feedback first</a><label className="field-label">Type DELETE to confirm<Input value={confirmation} onChange={e=>setConfirmation(e.target.value)} autoComplete="off"/></label>{error&&<p className="form-error" role="alert">{error}</p>}<div className="form-actions"><Button variant="outline" disabled={pending} onClick={()=>setOpen(false)}>Keep my account</Button><Button disabled={pending||confirmation!=='DELETE'} onClick={()=>void remove()}>Delete permanently</Button></div></DialogContent></Dialog>{!open&&error&&<p role="alert">{error}</p>}</section>;
}
export function LegalConsent({uid,onAccepted}:{uid:string;onAccepted:()=>void}){
 const [accepted,setAccepted]=useState(false),[pending,setPending]=useState(false),[error,setError]=useState('');
 const submit=async()=>{setPending(true);setError('');try{await communityAction({action:'acceptTerms',accepted,version:'2026-10-03'});onAccepted();}catch(e){setError((e as Error).message);}finally{setPending(false);}};
 return <main className="onboarding-shell"><section className="onboarding-card"><h1>Your writing remains yours.</h1><p>We’ve added member controls and written down how the workshop handles your contributions and data. Please review the policies before continuing.</p><p className="legal-links"><a href="/terms" target="_blank" rel="noreferrer">Terms of use</a><a href="/privacy" target="_blank" rel="noreferrer">Privacy policy</a><a href="/rights" target="_blank" rel="noreferrer">Writer rights</a></p><label className="settings-check"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/>I meet the age and permission requirements and agree to the terms. I have read the privacy policy.</label>{error&&<p className="form-error" role="alert">{error}</p>}<Button disabled={pending||!accepted} onClick={()=>void submit()}>Continue to the workshop</Button><p className="fine-print">Policy version: October 3, 2026. Operator: Tiernan Lindauer, Texas, United States.</p><AccountControls uid={uid} deletionOnly/><a className="text-link" href="/api/auth/logout">Sign out</a></section></main>;
}
