'use client';
import {useState} from 'react';
import {BookOpen,Sparkles,Flag} from 'lucide-react';
import {Button} from './ui/button';
import {Input} from './ui/input';
import {Textarea} from './ui/textarea';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from './ui/dialog';
import {usePagedList,PageMore} from './paged-list';
import {communityAction,useJson} from '@/hooks/use-community';
import type {Work} from '@/app/data';
type Feature={id:string;title:string;author:string;authorId:string;genre:string;words:number;warning:string;mature:boolean;note:string;day:string};
export function ShowcaseCard({onRead,onAuthor}:{onRead:(id:string)=>void;onAuthor:(id:string)=>void}){
 const resource=useJson<{showcase:Feature|null}>('/api/community?section=showcase');const w=resource.data?.showcase;
 if(!w)return null;
 return <section className="showcase-card"><div className="showcase-kicker"><Sparkles size={15}/>Today’s showcase <span>{w.day} · UTC</span></div><h2><button onClick={()=>onRead(w.id)}>{w.title}</button></h2><p className="work-byline">by <button className="author-link" onClick={()=>onAuthor(w.authorId)}>{w.author}</button> · {w.genre} · {w.words.toLocaleString()} words</p><p className="showcase-note">{w.note}</p>{(w.warning||w.mature)&&<p className="fine-print">Content note: {w.warning||'Mature themes'}</p>}<Button variant="outline" onClick={()=>onRead(w.id)}><BookOpen size={14}/>Read the showcase</Button><p className="fine-print">Writer opted in · Selected by the operator · Separate from the critique queue</p></section>;
}
export function ShowcaseConsent({work,onChanged}:{work:Work;onChanged?:()=>void}){
 const [open,setOpen]=useState(false),[optIn,setOptIn]=useState(!!work.showcaseOptIn),[pending,setPending]=useState(false),[error,setError]=useState('');
 if(['draft','withdrawn'].includes(work.status)||work.authorId.startsWith('sample-'))return null;
 const save=async()=>{setPending(true);setError('');try{await communityAction({action:'showcaseConsent',id:work.id,optIn});setOpen(false);onChanged?.();window.dispatchEvent(new Event('opendraft:requests'));}catch(e){setError((e as Error).message);}finally{setPending(false);}};
 return <><Button variant="outline" onClick={()=>{setOptIn(!!work.showcaseOptIn);setOpen(true);}}><Sparkles size={14}/>Showcase settings</Button><Dialog open={open} onOpenChange={value=>{if(!pending)setOpen(value);}}><DialogContent className="compact-dialog"><DialogTitle>Give this work a chance to shine</DialogTitle><DialogDescription>One opt-in work is showcased each day. The operator chooses, with rotation across authors and genres. This does not change your critique queue or credits.</DialogDescription><label className="settings-check"><input type="checkbox" checked={optIn} disabled={pending} onChange={e=>setOptIn(e.target.checked)}/>Allow this published work to appear in the daily showcase</label><p className="fine-print">Showcase participation is optional. Jev may evaluate opted-in writing under the workshop terms through Vercel AI Gateway and TypeSafe AI; only the operator sees showcase scores. No-training routing is required; provider retention still applies. Turning showcase participation off clears stored showcase assessments.</p>{error&&<p role="alert" className="form-error">{error}</p>}<div className="form-actions"><Button variant="outline" disabled={pending} onClick={()=>setOpen(false)}>Cancel</Button><Button disabled={pending} onClick={()=>void save()}>{pending?'Saving…':'Save showcase settings'}</Button></div></DialogContent></Dialog></>;
}
type Case={id:string;kind?:string;name?:string;email?:string;senderId?:string;userId?:string;messageId?:string;body:string;reason?:string;status:string;resolution:string;createdAt:number;resolvedAt?:number};
type Candidate={id:string;title:string;author:string;authorId:string;genre:string;words:number;aiShowcaseConsent:boolean;aiAssessment:string};
type Assessment={model:string;scores:Record<string,number>};
type Scheduled={id:string;day:string;title:string;author:string;genre:string;note:string;workId:string};
export function AdminCommunityPanel({onRead,onChanged,requestCounts={cases:0,legal:0}}:{requestCounts?:{cases:number;legal:number};onRead:(id:string)=>void;onChanged?:()=>void}){
 const [dateRange]=useState(()=>({min:new Date().toISOString().slice(0,10),max:new Date(Date.now()+30*86400000).toISOString().slice(0,10)}));
 const [tab,setTab]=useState('cases'),[filter,setFilter]=useState('open'),[revision,setRevision]=useState(0),[day,setDay]=useState(new Date().toISOString().slice(0,10)),[pending,setPending]=useState(''),[error,setError]=useState(''),[decision,setDecision]=useState<Record<string,unknown>|null>(null),[reason,setReason]=useState(''),[choice,setChoice]=useState<Candidate|null>(null),[note,setNote]=useState(''),[scores,setScores]=useState<Record<string,Assessment>>({});
 const cases=usePagedList<Case>('/api/community?section='+tab+'&status='+filter+'&pending='+(tab==='cases'?requestCounts.cases:requestCounts.legal),['cases','legal'].includes(tab),revision);
 const candidates=usePagedList<Candidate>('/api/community?section=candidates&day='+day,tab==='showcase',revision);
 const scheduled=usePagedList<Scheduled>('/api/community?section=scheduled',tab==='showcase',revision);
 const circles=usePagedList<{id:string;name:string;description:string}>('/api/community?section=orphanedCircles',tab==='circles',revision);
 const run=async(body:Record<string,unknown>)=>{const key=String(body.id||body.day||body.action);setPending(key);setError('');try{const result=await communityAction<{assessment?:Assessment}>(body);if(result.assessment){const assessment=result.assessment;setScores(old=>({...old,[key]:assessment}));}setRevision(n=>n+1);setDecision(null);if(body.action==='pickShowcase')setChoice(null);onChanged?.();}catch(e){setError((e as Error).message);}finally{setPending('');}};
 return <section className="community-admin"><h2 className="section-title"><Flag size={17}/>Member safety &amp; showcase</h2><div className="friend-tabs">{[['cases','Message reports'],['legal','Contact & legal'],['showcase','Daily showcase'],['circles','Managed circles']].map(([key,label])=><button key={key} className={tab===key?'active':''} aria-pressed={tab===key} onClick={()=>{setTab(key);setError('');}}>{label}{(key==='cases'?requestCounts.cases:key==='legal'?requestCounts.legal:0)>0&&<span className="request-count" aria-label="Open requests">{key==='cases'?requestCounts.cases:requestCounts.legal}</span>}</button>)}</div>{error&&!decision&&!choice&&<p className="form-error" role="alert">{error}</p>}
 {['cases','legal'].includes(tab)&&<><label className="admin-filter">Status<select className="form-select" value={filter} onChange={e=>setFilter(e.target.value)}><option value="open">Open requests</option><option value="resolved">Decision history</option><option value="all">All</option></select></label><p className="fine-print">Private to the operator. Preserve only the evidence needed for the case; record the outcome and any retention review in the decision.</p>{!cases.items.length&&!cases.loading&&!cases.error&&<p className="fine-print">No requests in this view.</p>}{cases.items.map(item=><article className="community-case" key={item.id}><header><b>{tab==='legal'?item.kind+' · '+item.name:'Incoming-message report'}</b><span className="tag">{item.status}</span></header><p>{item.reason||item.body}</p>{tab==='cases'&&<details><summary>Reported message evidence</summary><blockquote>{item.body}</blockquote><p className="fine-print">Sender: {item.senderId} · Reporter: {item.userId} · Message: {item.messageId}</p></details>}{tab==='legal'&&<p className="fine-print">Reply contact: {item.email}</p>}<p className="fine-print">{new Date(item.createdAt).toLocaleString()} · Reference {item.id}</p>{item.resolution&&<p><b>Decision:</b> {item.resolution} {item.resolvedAt&&<small>· {new Date(item.resolvedAt).toLocaleString()}</small>}</p>}{item.status==='open'&&<Button variant="outline" onClick={()=>{setReason('');setError('');setDecision({action:tab==='legal'?'resolveLegal':'resolveCase',id:item.id});}}>Record decision &amp; resolve</Button>}{item.status==='resolved'&&item.body!=='[Evidence removed after retention review]'&&<Button variant="outline" onClick={()=>{setReason('');setError('');setDecision({action:tab==='legal'?'redactLegal':'redactCase',id:item.id});}}>Remove evidence after retention review</Button>}</article>)}<PageMore page={cases} label="Earlier requests"/></>}
 {tab==='showcase'&&<><p className="fine-print">Choose one opt-in published work per day (UTC). An author can appear once in 30 days. Rotate genres when another eligible genre is available. Read the work before choosing; Jev is optional assistance, not a verdict. Reading earns no credits.</p><label className="field-label showcase-date">Showcase date<Input type="date" min={dateRange.min} max={dateRange.max} value={day} onChange={e=>{if(e.target.value)setDay(e.target.value);}}/></label>{!candidates.items.length&&!candidates.loading&&!candidates.error&&<p className="fine-print">No eligible opt-in works for this date yet.</p>}{candidates.items.map(work=>{let assessment=scores[work.id];if(!assessment&&work.aiAssessment){try{assessment=JSON.parse(work.aiAssessment);}catch{/* Older invalid scores do not prevent selection. */}}return <article className="community-case" key={work.id}><header><button className="work-title" onClick={()=>onRead(work.id)}>{work.title}</button><span className="tag">{work.genre}</span></header><p className="fine-print">{work.author} · {work.words.toLocaleString()} words · {work.aiShowcaseConsent?'Jev evaluation available under workshop terms':'Writer has not accepted updated terms'}</p>{assessment&&<p className="assessment">Jev assistance: {Object.entries(assessment.scores).map(([label,score])=>label+' '+score+'/100').join(' · ')}</p>}<div className="form-actions">{work.aiShowcaseConsent&&<Button variant="outline" disabled={!!pending} onClick={()=>void run({action:'evaluateShowcase',id:work.id})}>{pending===work.id?'Evaluating…':'Evaluate with Jev'}</Button>}<Button disabled={!!pending} onClick={()=>{setChoice(work);setNote('');setError('');}}>Choose for {day}</Button></div></article>;})}<PageMore page={candidates} label="More candidates"/><h3>Showcase schedule &amp; history</h3>{scheduled.items.map(item=><article className="community-case" key={item.id}><header><b>{item.day} · {item.title}</b><span className="tag">{item.genre}</span></header><p>{item.author} · {item.note}</p><Button variant="outline" disabled={!!pending} onClick={()=>{setReason('');setDecision({action:'clearShowcase',day:item.day});}}>Remove from schedule</Button></article>)}<PageMore page={scheduled} label="Earlier showcases"/></>}
 {tab==='circles'&&<><p className="fine-print">Circles left by deleted accounts remain readable. Adopt a circle to manage it and send bulletins.</p>{circles.items.map(circle=><article className="community-case" key={circle.id}><h3>{circle.name}</h3><p>{circle.description}</p><Button disabled={!!pending} onClick={()=>{setReason('');setDecision({action:'adoptCircle',id:circle.id});}}>Adopt as operator</Button></article>)}{!circles.items.length&&!circles.loading&&!circles.error&&<p className="fine-print">No circles need an owner.</p>}<PageMore page={circles}/></>}
 <Dialog open={!!decision} onOpenChange={v=>{if(!v&&!pending)setDecision(null);}}><DialogContent className="compact-dialog"><DialogTitle>Record an operator decision</DialogTitle><DialogDescription>Describe what you checked and the outcome. Evidence removal clears message/report details or contact details permanently, while preserving the decision and reference. Record why retention is no longer needed.</DialogDescription><label className="field-label">Decision / reason<Textarea minLength={5} maxLength={500} rows={5} value={reason} onChange={e=>setReason(e.target.value)}/></label>{error&&<p role="alert" className="form-error">{error}</p>}<div className="form-actions"><Button variant="outline" disabled={!!pending} onClick={()=>setDecision(null)}>Cancel</Button><Button disabled={!!pending||reason.trim().length<5} onClick={()=>{if(decision)void run({...decision,reason});}}>Apply decision</Button></div></DialogContent></Dialog>
 <Dialog open={!!choice} onOpenChange={v=>{if(!v&&!pending)setChoice(null);}}><DialogContent className="compact-dialog"><DialogTitle>Showcase {choice?.title}</DialogTitle><DialogDescription>This will replace any selection for {day}. Confirm you have read the work and write a short human introduction for the dashboard.</DialogDescription><label className="field-label">Why readers should take a look<Textarea minLength={10} maxLength={500} rows={4} value={note} onChange={e=>setNote(e.target.value)}/></label>{error&&<p className="form-error" role="alert">{error}</p>}<div className="form-actions"><Button variant="outline" disabled={!!pending} onClick={()=>setChoice(null)}>Cancel</Button><Button disabled={!!pending||note.trim().length<10} onClick={()=>void run({action:'pickShowcase',id:choice?.id,day,note})}>Publish showcase selection</Button></div></DialogContent></Dialog>
 </section>;
}
