'use client';
import {useEffect,useState} from 'react';
import {Button} from './ui/button';
type Options={workId:string;feedUpdates:boolean;emailUpdates:boolean;emailAvailable:boolean;read:boolean;reminderAt:number|null};
export function WorkReadingOptions({workId,uid,version}:{workId:string;uid:string;version:number}){
 const [options,setOptions]=useState<Options|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[custom,setCustom]=useState('');
 useEffect(()=>{const controller=new AbortController();fetch('/api/work-updates?workId='+encodeURIComponent(workId),{cache:'no-store',signal:controller.signal}).then(async response=>{const data=await response.json() as Options&{error?:string};if(!response.ok)throw new Error(data.error);setOptions(data);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[workId,uid,version]);
 const save=async(change:Record<string,unknown>)=>{setBusy(true);setError('');try{const response=await fetch('/api/work-updates',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'preference',workId,...change})});const data=await response.json() as Options&{error?:string};if(!response.ok)throw new Error(data.error);setOptions(data);window.dispatchEvent(new Event('opendraft:updates'));}catch(e){setError((e as Error).message||'Could not save reading options.');}finally{setBusy(false);}};
 return <details className="work-reading-options"><summary className="reading-settings-button">Reading &amp; updates{options?.read?' · Read':''}</summary><div className="work-reading-panel">{options?<>
 <label className="settings-check"><input type="checkbox" disabled={busy} checked={options.read} onChange={e=>void save({read:e.target.checked})}/>Mark this work as read</label><p className="fine-print">Only you see this marker. It records your choice, not proof of reading. Marking read clears your reminder.</p>
 <label className="settings-check"><input type="checkbox" disabled={busy} checked={options.feedUpdates} onChange={e=>void save({feedUpdates:e.target.checked})}/>Get feed updates about this work</label>
 <label className="settings-check"><input type="checkbox" disabled={busy||(!options.emailAvailable&&!options.emailUpdates)} checked={options.emailUpdates} onChange={e=>void save({emailUpdates:e.target.checked})}/>Get email updates about this work</label>{!options.emailAvailable&&<p className="fine-print">Email delivery is not available yet. Feed updates and reminders work here in the workshop.</p>}
 <p className="fine-print">Updates cover new feedback, revisions, entering the reading room, and completion of requested critiques.</p>
 <strong>Set a reading reminder</strong>{options.reminderAt&&<p role="status" className="fine-print">Reminder: {new Date(options.reminderAt).toLocaleString()}</p>}<div className="form-actions"><Button variant="outline" disabled={busy} onClick={()=>void save({reminderAt:Date.now()+86400000})}>Tomorrow</Button><Button variant="outline" disabled={busy} onClick={()=>void save({reminderAt:Date.now()+7*86400000})}>In a week</Button>{options.reminderAt&&<Button variant="ghost" disabled={busy} onClick={()=>void save({reminderAt:null})}>Clear reminder</Button>}</div>
 <form onSubmit={e=>{e.preventDefault();const reminderAt=new Date(custom).getTime();if(Number.isFinite(reminderAt))void save({reminderAt});}}><label className="field-label">Choose a time<input type="datetime-local" required value={custom} onChange={e=>setCustom(e.target.value)}/></label><Button variant="outline" disabled={busy||!custom}>Set reminder</Button></form><p className="fine-print">Reminders appear in Work updates when you next visit. A new revision has its own read marker.</p>
 </>:!error&&<p className="fine-print">Loading reading options…</p>}{error&&<p role="alert" className="form-error">{error}</p>}</div></details>;
}
