import { pgTable, text, integer, bigint, uniqueIndex, index } from 'drizzle-orm/pg-core';
export const profiles = pgTable('profiles', {id:text('id').primaryKey(),name:text('name').notNull(),bio:text('bio').notNull().default(''),credits:integer('credits').notNull().default(5),createdAt:bigint('created_at', {mode:'number'}).notNull()});
export const works = pgTable('works',{id:text('id').primaryKey(),authorId:text('author_id').notNull(),author:text('author').notNull(),title:text('title').notNull(),genre:text('genre').notNull(),kind:text('kind').notNull(),stage:text('stage').notNull(),content:text('content').notNull(),request:text('request').notNull(),status:text('status').notNull().default('draft'),version:integer('version').notNull().default(1),createdAt:bigint('created_at', {mode:'number'}).notNull(),words:integer('words').notNull(),warning:text('warning').notNull().default('')},t=>[index('idx_works_status_created').on(t.status,t.createdAt),index('idx_works_author').on(t.authorId)]);
export const reviews = pgTable('reviews',{id:text('id').primaryKey(),workId:text('work_id').notNull().references(()=>works.id),userId:text('user_id').notNull().references(()=>profiles.id),author:text('author').notNull(),strengths:text('strengths').notNull(),suggestions:text('suggestions').notNull(),overall:text('overall').notNull(),annotation:text('annotation').notNull().default(''),quote:text('quote').notNull().default(''),version:integer('version').notNull(),reward:integer('reward').notNull(),helpful:integer('helpful').notNull().default(0),createdAt:bigint('created_at', {mode:'number'}).notNull()},t=>[uniqueIndex('idx_reviews_work_user_version').on(t.workId,t.userId,t.version),index('idx_reviews_user').on(t.userId)]);
export const bookmarks = pgTable('bookmarks',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>profiles.id),workId:text('work_id').notNull().references(()=>works.id)},t=>[uniqueIndex('idx_bookmarks_user_work').on(t.userId,t.workId)]);
export const circles = pgTable('circles',{id:text('id').primaryKey(),name:text('name').notNull(),description:text('description').notNull(),genre:text('genre').notNull(),ownerId:text('owner_id').notNull()});
export const memberships = pgTable('memberships',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>profiles.id),circleId:text('circle_id').notNull().references(()=>circles.id)},t=>[uniqueIndex('idx_membership_circle_user').on(t.circleId,t.userId)]);
export const posts = pgTable('posts',{id:text('id').primaryKey(),circleId:text('circle_id').notNull().references(()=>circles.id),userId:text('user_id').notNull().references(()=>profiles.id),author:text('author').notNull(),body:text('body').notNull(),createdAt:bigint('created_at', {mode:'number'}).notNull()},t=>[index('idx_posts_circle_created').on(t.circleId,t.createdAt)]);
export const creditEvents = pgTable('credit_events',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>profiles.id),amount:integer('amount').notNull(),reason:text('reason').notNull(),createdAt:bigint('created_at', {mode:'number'}).notNull()},t=>[index('idx_credits_user').on(t.userId)]);
export const reports = pgTable('reports',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>profiles.id),workId:text('work_id').notNull().references(()=>works.id),reason:text('reason').notNull(),createdAt:bigint('created_at', {mode:'number'}).notNull()},t=>[uniqueIndex('idx_reports_work_user').on(t.workId,t.userId)]);
export const settings = pgTable('settings',{id:text('id').primaryKey(),value:text('value').notNull()});

